name: Build Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17.0.13
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.0.13'  

      - name: Build with Maven
        run: mvn clean install

